# Generated by Django 4.2.1 on 2023-05-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_order_total_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="price",
            field=models.IntegerField(),
        ),
    ]
