# Generated by Django 4.2.1 on 2023-05-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_alter_meal_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.IntegerField(null=True),
        ),
    ]
