# Generated by Django 4.2.1 on 2023-05-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_order_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
