# Generated by Django 4.2.1 on 2023-05-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0008_alter_order_total_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.IntegerField(null=True),
        ),
    ]
